language: python

matrix:
  include:
    - python: "2.7"
      env: ANSIBLE_VERSION=ppa:ansible/ansible
    - python: "2.7"
      env: ANSIBLE_VERSION=ppa:ansible/ansible-1.9

before_install:
 - sudo apt-get install software-properties-common -qq
 - sudo apt-add-repository $ANSIBLE_VERSION -qq
 - sudo apt-get update -qq
 - sudo apt-get install ansible -qq

script:
  - echo localhost > inventory
  - ansible-playbook -i inventory --connection=local --sudo -vv test/test.yml