---
# Setup folders
- name: ANSISTRANO | Ensure deployment base path exists
  file: state=directory recurse=yes path={{ ansistrano_deploy_to }}

- name: ANSISTRANO | Ensure releases folder exists
  file: state=directory recurse=yes path={{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}

- name: ANSISTRANO | Ensure shared elements folder exists
  file: state=directory recurse=yes path={{ ansistrano_deploy_to }}/shared
