---
# Symlinks shared paths
- name: ANSISTRANO | Create softlinks for shared paths
  file: state=link path={{ ansistrano_release_path.stdout }}/{{ item }} src={{ ansistrano_deploy_to }}/shared/{{ item }}
  with_items: ansistrano_shared_paths
