---
# Update code deployment step
- name: Ensure deployment base path exists
  file: state=directory recurse=yes path={{ ansistrano_deploy_to }}

- name: Ensure releases folder exists
  file: state=directory recurse=yes path={{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}

- name: Ensure shared elements folder exists
  file: state=directory recurse=yes path={{ ansistrano_deploy_to }}/shared

- name: Get release timestamp
  command: date +%Y%m%d%H%M%S
  register: timestamp

- name: Get release path
  command: echo "{{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}/{{ timestamp.stdout }}"
  register: release_path

- name: Get releases path
  command: echo "{{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}"
  register: releases_path

- name: RSYNC | Deploy using Rsync strategy
  include: update-code/rsync.yml
  when: ansistrano_deploy_via == 'rsync'

- name: SCP | Deploy using SCP strategy
  include: update-code/copy.yml
  when: ansistrano_deploy_via == 'copy'

- name: GIT | Deploy using Git strategy
  include: update-code/git.yml
  when: ansistrano_deploy_via == 'git'

- name: Copy release version into REVISION file
  shell: echo {{ timestamp.stdout }} > {{ release_path.stdout }}/REVISION

- name: Touches up the release code
  shell: chmod -R -- g+w {{ release_path.stdout }} && chmod -R g+w {{ release_path.stdout }}
