---
# Update code deployment step
- name: ANSISTRANO | Ensure deployment base path exists
  file: state=directory recurse=yes path={{ ansistrano_deploy_to }}

- name: ANSISTRANO | Ensure releases folder exists
  file: state=directory recurse=yes path={{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}

- name: ANSISTRANO | Ensure shared elements folder exists
  file: state=directory recurse=yes path={{ ansistrano_deploy_to }}/shared

- name: ANSISTRANO | Get release timestamp
  command: date +%Y%m%d%H%M%S
  register: ansistrano_timestamp

- name: ANSISTRANO | Get release path
  command: echo "{{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}/{{ ansistrano_timestamp.stdout }}"
  register: ansistrano_release_path

- name: ANSISTRANO | Get releases path
  command: echo "{{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}"
  register: ansistrano_releases_path

- name: ANSISTRANO | Get shared path (in rsync case)
  command: echo "{{ ansistrano_deploy_to }}/shared/.shared-copy"
  register: ansistrano_shared_path
  when: ansistrano_deploy_via == 'rsync'

- name: ANSISTRANO | Rsync application files to remote shared copy (in rsync case)
  synchronize: src={{ ansistrano_deploy_from }} dest={{ ansistrano_shared_path.stdout }} recursive=yes delete=yes archive=yes compress=yes rsync_opts={{ ansistrano_rsync_extra_params }}
  when: ansistrano_deploy_via == 'rsync'

- name: ANSISTRANO | Deploy existing code to servers
  command: cp -pr {{ ansistrano_shared_path.stdout }} {{ ansistrano_release_path.stdout }}
  when: ansistrano_deploy_via == 'rsync'

- name: ANSISTRANO | Deploy existing code to remote servers
  copy: src={{ ansistrano_deploy_from }} dest={{ ansistrano_release_path.stdout }}
  when: ansistrano_deploy_via == 'copy'

- name: ANSISTRANO | Update remote repository
  git: repo={{ ansistrano_git_repo }} dest={{ ansistrano_deploy_to }}/shared version={{ ansistrano_git_branch }} accept_hostkey=true update=yes
  when: ansistrano_deploy_via == 'git'

- name: ANSISTRANO | Export a copy of the repo
  command: git checkout-index -f -a --prefix="{{ ansistrano_release_path.stdout }}/"
  args:
    chdir: "{{ ansistrano_deploy_to }}/shared"
  when: ansistrano_deploy_via == 'git'

- name: ANSISTRANO | Deploy code from to servers
  git: repo={{ ansistrano_deploy_from}} dest={{ ansistrano_release_path.stdout }} accept_hostkey=true
  when: ansistrano_deploy_via == 'git'

- name: ANSISTRANO | Copy release version into REVISION file
  shell: echo {{ ansistrano_timestamp.stdout }} > {{ ansistrano_release_path.stdout }}/REVISION

- name: ANSISTRANO | Touches up the release code
  shell: chmod -R -- g+w {{ ansistrano_release_path.stdout }} && chmod -R g+w {{ ansistrano_release_path.stdout }}
